services:
  postgres:
    image: postgres:15
    container_name: ${PG_CONTAINER}
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "${PG_PORT}:${PG_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:latest
    container_name: ${ADMINER_CONTAINER}
    ports:
      - "${ADMINER_PORT}:${HTTP_PORT}"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata: