spring:
  config:
    import: optional:classpath:application-base.yml
  jpa:
    properties:
      hibernate:
        default_schema: ${BANKING_SCHEMA}
  flyway:
    enabled: ${BANKING_FLYWAY_ENABLED}
    schemas: ${BANKING_SCHEMA}