spring:
  datasource:
    url: ${PG_URL}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    flyway:
      enabled: true
      locations: classpath:db
      baseline-on-migrate: true
server:
  port: ${HTTP_PORT}