name: Build (push+PR)

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: build-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Build (skip tests)
        run: mvn -B -ntp -DskipTests package
