name: ci
on:
  push: { branches: [ main ] }
  pull_request:
permissions:
  contents: read
  security-events: write
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'
      - name: Build & test (no Docker needed)
        run: mvn -B -e -ntp clean verify
      - name: Upload surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with: { name: surefire-reports, path: '**/target/surefire-reports/*.xml' }

  codeql:
    uses: github/codeql-action/.github/workflows/codeql.yml@v3
    with:
      languages: 'java'
