name: publish
on:
  push:
    tags: [ 'v*' ]
permissions:
  contents: read
  packages: write
  id-token: write
env:
  IMAGE_OWNER: ${{ github.repository_owner }}
  VERSION: ${{ github.ref_name }}          # v0.1.0
  SHA_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ 'api-gateway', 'user-management', 'bank-accounts', 'bills' ]
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      - name: Package service
        working-directory: ${{ matrix.service }}
        run: mvn -B -ntp -DskipTests package

      - name: Build & push image
        working-directory: ${{ matrix.service }}
        run: |
          SVC=${{ matrix.service }}
          IMG=ghcr.io/${{ env.IMAGE_OWNER }}/finance-hub-$SVC
          docker build -t $IMG:${{ env.VERSION }} -t $IMG:${{ env.SHA_TAG }} .
          docker push $IMG:${{ env.VERSION }}
          docker push $IMG:${{ env.SHA_TAG }}
